version: "3"

services:
  redis:
    image: "redis"
    restart: unless-stopped
    # ports:
    #   - 6379:6379
    volumes:
      - redis:/data
    command: ["redis-server", "--appendonly yes"]
  postgres:
    image: "postgres"
    restart: unless-stopped
    # ports:
    #   - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=${DATABASE_NAME}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    command: yarn dev:watch
    volumes:
      - ./server/node_modules:/app/node_modules
      - ./server/src:/app/src
    depends_on:
      - postgres
      - redis
    env_file: 
      - .env
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: yarn dev
    volumes:
      - ./client/node_modules:/app/node_modules
      - ./client/.next:/app/.next
      - ./client/src:/app/src
    depends_on:
      - server
    env_file:
      - .env
volumes:
  postgres:
  redis:
